import { Technician, Job, TechnicianStatus, Zone, DashboardMetrics } from './types';

// Zones loosely mapping to West Kensington areas
export const ZONES: Zone[] = [
  { id: 'Z1', name: 'Barons Court', color: 'zone-1', x: 5, y: 35, width: 40, height: 30 },
  { id: 'Z2', name: 'Olympia', color: 'zone-2', x: 5, y: 5, width: 40, height: 25 },
  { id: 'Z3', name: 'Earls Court', color: 'zone-3', x: 50, y: 5, width: 45, height: 45 },
  { id: 'Z4', name: 'Fulham Reach', color: 'zone-4', x: 50, y: 55, width: 45, height: 40 },
];

export const MOCK_TECHNICIANS: Technician[] = [
  {
    id: 'T-101',
    name: 'S. Chen',
    avatar: 'https://picsum.photos/50/50?random=1',
    vehicleId: 'VAN-042',
    status: TechnicianStatus.Working,
    currentJobId: 'J-204',
    location: { x: 25, y: 42 }, // Near Barons Court
    zone: 'Z1',
    batteryLevel: 85,
    fuelLevel: 40,
    efficiencyScore: 94,
    jobsCompletedToday: 3,
    billableRate: 120,
  },
  {
    id: 'T-102',
    name: 'M. Ross',
    avatar: 'https://picsum.photos/50/50?random=2',
    vehicleId: 'VAN-015',
    status: TechnicianStatus.EnRoute,
    currentJobId: 'J-205',
    location: { x: 80, y: 15 }, // Earls Court Rd
    zone: 'Z2',
    batteryLevel: 62,
    fuelLevel: 80,
    efficiencyScore: 88,
    jobsCompletedToday: 2,
    billableRate: 110,
  },
  {
    id: 'T-103',
    name: 'J. Pearson',
    avatar: 'https://picsum.photos/50/50?random=3',
    vehicleId: 'VAN-088',
    status: TechnicianStatus.Available,
    location: { x: 15, y: 85 }, // Lillie Rd
    zone: 'Z3',
    batteryLevel: 98,
    fuelLevel: 20,
    efficiencyScore: 98,
    jobsCompletedToday: 4,
    billableRate: 150,
  },
  {
    id: 'T-104',
    name: 'L. Litt',
    avatar: 'https://picsum.photos/50/50?random=4',
    vehicleId: 'VAN-099',
    status: TechnicianStatus.OnBreak,
    location: { x: 90, y: 60 }, // Brompton Cemetery area
    zone: 'Z4',
    batteryLevel: 45,
    fuelLevel: 90,
    efficiencyScore: 72,
    jobsCompletedToday: 1,
    billableRate: 95,
  },
  {
    id: 'T-105',
    name: 'H. Specter',
    avatar: 'https://picsum.photos/50/50?random=5',
    vehicleId: 'VAN-100',
    status: TechnicianStatus.Working,
    currentJobId: 'J-206',
    location: { x: 45, y: 12 }, // Talgarth Rd
    zone: 'Z1',
    batteryLevel: 78,
    fuelLevel: 55,
    efficiencyScore: 99,
    jobsCompletedToday: 5,
    billableRate: 250,
  },
];

export const MOCK_JOBS: Job[] = [
  {
    id: 'J-204',
    customer: 'Nakatomi Plaza',
    type: 'HVAC',
    priority: 'High',
    status: 'In Progress',
    estimatedValue: 1200,
    address: '2121 Talgarth Rd',
    zone: 'Z1',
    scheduledTime: '10:00',
    location: { x: 28, y: 40 },
  },
  {
    id: 'J-205',
    customer: 'Cyberdyne Systems',
    type: 'Network',
    priority: 'Critical',
    status: 'Assigned',
    estimatedValue: 4500,
    address: '181 Warwick Rd',
    zone: 'Z2',
    scheduledTime: '11:30',
    location: { x: 75, y: 18 },
  },
  {
    id: 'J-206',
    customer: 'Stark Industries',
    type: 'Security',
    priority: 'Medium',
    status: 'In Progress',
    estimatedValue: 3000,
    address: '108 North End Rd',
    zone: 'Z1',
    scheduledTime: '09:00',
    location: { x: 40, y: 10 },
  },
  {
    id: 'J-207',
    customer: 'Wayne Enterprises',
    type: 'Service',
    priority: 'Low',
    status: 'Unassigned',
    estimatedValue: 850,
    address: '1007 Lillie Rd',
    zone: 'Z3',
    scheduledTime: '14:00',
    location: { x: 20, y: 80 },
  },
  {
    id: 'J-208',
    customer: 'Umbrella Corp',
    type: 'Cleanup',
    priority: 'High',
    status: 'Unassigned',
    estimatedValue: 2200,
    address: '5454 Cromwell Rd',
    zone: 'Z4',
    scheduledTime: '15:15',
    location: { x: 60, y: 5 },
  },
  {
    id: 'J-209',
    customer: 'Massive Dynamic',
    type: 'Server',
    priority: 'Critical',
    status: 'Unassigned',
    estimatedValue: 5000,
    address: '655 West Ken St',
    zone: 'Z1',
    scheduledTime: '13:00',
    location: { x: 45, y: 45 },
  },
];

export const INITIAL_METRICS: DashboardMetrics = {
  activeJobs: 3,
  revenueToDate: 14500,
  avgResponseTime: 42,
  fleetEfficiency: 92,
  billableHours: 128,
};